FROM bitnami/git

WORKDIR /npm-nostrify-publisher

# Keyboard & Timezone
ENV LANG=C.UTF-8
ENV TZ=America/Sao_Paulo

ENV LANG C.UTF-8
ENV TZ America/Sao_Paulo

# The run the start script
CMD [ "/bin/bash" ]
